[application]
name = "emoji_picker"
default_platform = "desktop"

[bundle]
identifier = "dev.bajrangcoder.emoji_picker"
publisher = "Raunak Raj"
icon = ["assets/icon.png"]
short_description = "A simple emoji picker"
